//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZE.ADO.NetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsTable
    {
        public int ID { get; set; }
        public string Full_Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string User_Type { get; set; }
        public string Date_Time_Registered { get; set; }
        public string Email { get; set; }
        public string Image_Location { get; set; }
    }
}
