//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZE.ADO.NetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentsTable
    {
        public int ID { get; set; }
        public string Equipment { get; set; }
        public string Barcode { get; set; }
        public string Status { get; set; }
        public string Defective_Since { get; set; }
    }
}
