//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZE.ADO.NetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulesTable
    {
        public int ID { get; set; }
        public string Subject_Code { get; set; }
        public string Subject_Name { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public string Room { get; set; }
        public string Professor { get; set; }
        public string Year_Level { get; set; }
        public string Year_and_Section { get; set; }
    }
}
