//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZE.ADO.NetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTable
    {
        public int ID { get; set; }
        public string Student_Number { get; set; }
        public string Full_Name { get; set; }
        public string Year_and_Section { get; set; }
        public string Contact_Number { get; set; }
        public string Birthday { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Guardian { get; set; }
        public string Guardian_Number { get; set; }
        public string Year_Level { get; set; }
        public string Image_Location { get; set; }
    }
}
